In [1]:
import torch

In [2]:
# Создайте случайный FloatTensor размера 3x4x5
x_ft = torch.FloatTensor(3, 4, 5)
x_ft

tensor([[[4.6286e-38, 1.4854e-43, 0.0000e+00, 1.1388e-38, 1.4854e-43],
         [0.0000e+00, 1.0745e-38, 1.1429e-38, 5.0727e-43, 0.0000e+00],
         [1.1388e-38, 8.6600e-43, 0.0000e+00, 1.1388e-38, 1.2247e-42],
         [0.0000e+00, 1.1388e-38, 1.5835e-42, 0.0000e+00, 1.1388e-38]],

        [[1.9422e-42, 0.0000e+00, 1.1388e-38, 2.3009e-42, 0.0000e+00],
         [1.1388e-38, 2.6597e-42, 0.0000e+00, 1.1388e-38, 3.0184e-42],
         [0.0000e+00, 1.1388e-38, 3.3771e-42, 0.0000e+00, 2.7685e-33],
         [4.2980e-38, 0.0000e+00, 0.0000e+00, 1.7192e-37, 0.0000e+00]],

        [[0.0000e+00, 6.8768e-37, 0.0000e+00, 0.0000e+00, 2.7507e-36],
         [0.0000e+00, 0.0000e+00, 1.1003e-35, 0.0000e+00, 0.0000e+00],
         [4.4012e-35, 0.0000e+00, 0.0000e+00, 1.7605e-34, 0.0000e+00],
         [0.0000e+00, 7.0419e-34, 0.0000e+00, 0.0000e+00, 2.8167e-33]]])

In [3]:
# Выведите его форму (shape)
x_ft.size()

torch.Size([3, 4, 5])

In [4]:
# Приведите его к форме 6 X 10
x_ft_r = x_ft.reshape((6, 10))
x_ft_r.shape

torch.Size([6, 10])

In [5]:
# Умножьте его на вектор [1, 4, 2, 2, 1] поэлементно
x_ft @ torch.tensor([1, 4, 2, 2, 1], dtype=torch.float)

tensor([[6.9061e-38, 6.5837e-38, 3.4167e-38, 5.6941e-38],
        [2.2782e-38, 3.4176e-38, 2.7686e-33, 3.8682e-37],
        [5.5014e-36, 2.2006e-35, 3.9610e-34, 5.6335e-33]])

In [6]:
# Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
(x_ft_r @ torch.transpose(x_ft_r, 0, 1)).shape

torch.Size([6, 6])

In [7]:
# Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)
x = torch.tensor(1.0, requires_grad=True) 
z = torch.tensor(0.5, requires_grad=True) 
t = torch.tensor(2.0, requires_grad=True) 
y = x**3 + z - 75 * t
y.backward() 
x.grad, z.grad, t.grad 

(tensor(3.), tensor(1.), tensor(-75.))

In [8]:
# Создайте единичный тензор размера 5x6
xx = torch.ones(5, 6)
xx

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [9]:
# Переведите его в формат numpy
xx = xx.numpy()
xx

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)